### ISSUE TITLE
Publish the cli as installable via npm?

### ISSUE THREAD

**Issue by glenjamin** [auth0/repo-supervisor#6] opened 2017-07-03 13:18 UTC
Is there any reason this isn't a tool I can install via `npm install -g`?

If this is an explicit choice, it might be worth grabbing the name `repo-supervisor` on the npm registry to ensure someone doesn't put something malicious there?

**Comment by radekk** [comment] 2017-07-05 11:25
It was designed as a standalone tool and not a package that you can use in your projects. That's something we may consider in the future. I'm closing this since it's not a real issue but rather feature requests. I will reopen/update this issue if something will change.

Thanks for the suggestion with npm registry 👍

**Closed by radekk** 2017-07-05 11:25 UTC
Labels: enhancement
